services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - ./server:/app:delegated
    depends_on:
      - db
    env_file:
      - ./server/.env
    environment:
      DATABASE_NAME: task-manager-api
      DATABASE_USER: root
      DATABASE_PASS: password
      DATABASE_URI: mongodb://root:password@db:27017
    command: "npm run start:debug"

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   environment:
  #     NEXT_API_URL: http://localhost:3000
  #   env_file:
  #     - ./client/.env
  #   volumes:
  #     - ./client:/app
  #   restart: always
  #   ports:
  #     - 80:3000

  db:
    image: mongo:7.0.12
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: task-manager-api
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - server:/data/db

volumes:
  server: