FROM node:20-alpine as base

FROM base as builder

WORKDIR /app

COPY package*.json .
RUN npm ci

COPY . .

RUN npm run build

# --------------------------------------------

FROM base as production
WORKDIR /app

COPY package*.json .

RUN npm ci --only=production

COPY --from=builder /app/dist ./dist

CMD ["npm", "run", "start:prod"]